-- AlterTable
ALTER TABLE "Personagens" ADD COLUMN     "banner_url" TEXT,
ADD COLUMN     "carisma" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "constituicao" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "deslocamento" TEXT NOT NULL DEFAULT '9m',
ADD COLUMN     "destreza" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "forca" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "inteligencia" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mana_atual" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mana_max" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "nivel" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "sabedoria" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "vida_atual" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "vida_max" INTEGER NOT NULL DEFAULT 10;
